Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/FileName:
  Exclude:
  - 'Gemfile.local.rb'
  - 'Gemfile.local.example.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
    - 'script/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'config/unicorn.rb'
    - 'db/**/*'
    - 'vendor/bundle/**/*'
